// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Article
{
    public int ArticleId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Quantity { get; set; }

    public double Weight { get; set; }

    public double Volume { get; set; }

    public string PhotoUrls { get; set; } // JSON string to store list of photo URLs

    public virtual ICollection<TaskMission> Tasks { get; set; } = new List<TaskMission>();
}