// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Circuit
{
    public int CircuitId { get; set; }

    public int MissionId { get; set; }

    public DateTime DepartureDate { get; set; }

    public int DepartureSiteId { get; set; }

    public int ArrivalSiteId { get; set; }

    public virtual Mission Mission { get; set; }

    public virtual Site DepartureSite { get; set; }

    public virtual Site ArrivalSite { get; set; }

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();
}