// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using gestionMissionBack.Domain.Enums;

namespace gestionMissionBack.Domain.Entities;

public partial class Document
{
    public int DocumentId { get; set; }

    public int TaskId { get; set; }

    public string Name { get; set; }

    public DocumentType Type { get; set; }

    public string StoragePath { get; set; }

    public DateTime AddedDate { get; set; }

    public virtual TaskMission Task { get; set; }
}