// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using gestionMissionBack.Domain.Enums;
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Incident
{
    public int IncidentId { get; set; }

    public int MissionId { get; set; }

    public IncidentType Type { get; set; }

    public string Description { get; set; }

    public DateTime ReportDate { get; set; }

    public IncidentStatus Status { get; set; }

    public string? IncidentDocsUrls { get; set; }

    public virtual Mission Mission { get; set; }
}