// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using gestionMissionBack.Domain.Enums;

namespace gestionMissionBack.Domain.Entities;

public partial class MissionCost
{
    public int CostId { get; set; }

    public int MissionId { get; set; }

    public MissionCostType Type { get; set; }

    public double Amount { get; set; }

    public DateTime Date { get; set; }

    public string? ReceiptPhotoUrls { get; set; }

    public virtual Mission Mission { get; set; }
}