// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using gestionMissionBack.Domain.Enums;
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Mission
{
    public int MissionId { get; set; }

    public MissionType Type { get; set; }

    public int RequesterId { get; set; }

    public int DriverId { get; set; }

    public DateTime SystemDate { get; set; }

    public DateTime? DesiredDate { get; set; }

    public string Service { get; set; }

    //public int Quantity { get; set; }

    public string Receiver { get; set; }

    public MissionStatus Status { get; set; }

    public virtual ICollection<Circuit> Circuits { get; set; } = new List<Circuit>();

    public virtual User Driver { get; set; }

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<MissionCost> MissionCosts { get; set; } = new List<MissionCost>();

    public virtual User Requester { get; set; }

    public virtual ICollection<TaskMission> Tasks { get; set; } = new List<TaskMission>();

}