// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using gestionMissionBack.Domain.Enums;

namespace gestionMissionBack.Domain.Entities;

public partial class Notification
{
    public Notification()
    {
        // Set default values
        SentDate = DateTime.UtcNow;
        NotificationType = NotificationCategory.System;
        Priority = NotificationPriority.Normal;
        Status = NotificationStatus.Unread;
    }

    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public DateTime SentDate { get; set; }

    // New fields for enhanced notification management
    public NotificationCategory NotificationType { get; set; }
    public NotificationPriority Priority { get; set; }
    public NotificationStatus Status { get; set; }
    public string? RelatedEntityType { get; set; }
    public int? RelatedEntityId { get; set; }
    public DateTime? ExpiryDate { get; set; }

    public virtual User User { get; set; }
}