// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Route
{
    public int RouteId { get; set; }

    public int CircuitId { get; set; }

    public int DepartureSiteId { get; set; }

    public int ArrivalSiteId { get; set; }

    public double? DistanceKm { get; set; }

    public int Ordre { get; set; }

    public virtual Circuit Circuit { get; set; }

    public virtual Site DepartureSite { get; set; }

    public virtual Site ArrivalSite { get; set; }
}