// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using gestionMissionBack.Domain.Enums;
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class TaskMission
{
    public int TaskId { get; set; }

    public string Description { get; set; }

    public DateTime AssignmentDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    public TasksStatus Status { get; set; }

    public int SiteId { get; set; }

    public int? MissionId { get; set; }

    public bool IsFirstTask { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual Mission Mission { get; set; }

    public virtual Site Site { get; set; }

}