// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using gestionMissionBack.Domain.Enums;
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public DriverStatus? CurrentDriverStatus { get; set; }

    public virtual ICollection<Mission> MissionDrivers { get; set; } = new List<Mission>();

    public virtual ICollection<Mission> MissionRequesters { get; set; } = new List<Mission>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<VehicleReservation> VehicleReservations { get; set; } = new List<VehicleReservation>();

    public Role Role { get; set; } = null!;

}
