// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using gestionMissionBack.Domain.Enums;
using System;
using System.Collections.Generic;

namespace gestionMissionBack.Domain.Entities;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public VehicleType Type { get; set; }

    public string LicensePlate { get; set; }

    public bool Availability { get; set; }

    public double MaxCapacity { get; set; }

    public string PhotoUrls { get; set; } // JSON string to store list of photo URLs

    public virtual ICollection<VehicleReservation> VehicleReservations { get; set; } = new List<VehicleReservation>();
}