// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using gestionMissionBack.Domain.Enums;

namespace gestionMissionBack.Domain.Entities;

public partial class VehicleReservation
{
    public int ReservationId { get; set; }

    public int RequesterId { get; set; }

    public int VehicleId { get; set; }

    public bool RequiresDriver { get; set; }

    public string Departure { get; set; }

    public string Destination { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public VehicleReservationStatus Status { get; set; }

    public virtual User Requester { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}