global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API
  - job_name: 'mission-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend
  - job_name: 'mission-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # SQL Server (if metrics endpoint available)
  - job_name: 'mission-sqlserver'
    static_configs:
      - targets: ['sqlserver:1433']
    scrape_interval: 30s

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Jenkins (if running)
  - job_name: 'jenkins'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/prometheus'
    scrape_interval: 30s
